### ISSUE TITLE
"Amount" error en montos terminados en 8, o decimales en 8.

### ISSUE THREAD

**Issue by Deilur** [conekta/conekta-woocommerce#106]
Cuando alguien intenta pagar con tarjeta en montos terminados en 8, o con decimales con 8, el pago falla y dice que hay un error en el "amount". Lo he estado resolviendo dando $1 peso de descuento, pero es molesto y me hace perder ventas.

**Comment by silvaGarduno** [comment]
Hola @Deilur 

Me podrias apoyar con las versiones que manejas en tu tienda por favor, versiones de WordPress, WooCommerce y version de plugin Conekta.
