### ISSUE TITLE
Error: The company cannot process until risk approval is done.

### ISSUE THREAD

**Issue by vazquezcamp** [conekta/conekta-woocommerce#116]
Hola, últimamente he tenido algunos problemas con Conekta, hace días se podían realizar compras por método Oxxo pay sin problemas, hoy uno de nuestros clientes no informó sobre este error, el cual no deja crear los tickets para pagar por Oxxo. ¿A qué se debe?

**Comment by silvaGarduno** [comment]
Hola, buenas tardes @vazquezcamp, podrías comunicarte a soporte@conekta.com para revisar tu caso por favor.
