### ISSUE TITLE
Error: amount" no es mayor a -1.

### ISSUE THREAD

**Issue by vazquezcamp** [conekta/conekta-woocommerce#117]
Este error sale cuando se aplica un envío Gratis es decir $0 o una cantidad menor a $50 en el envío.
Funciona correctamente cuando el envío supera la cantidad de$50 o tiene precio fijo.

Versión woocommerce: 3.9.2
Versión Conekta: 3.8.1
Versión de Wordpress:  5.3.2

**Comment by silvaGarduno** [comment]
Hola @vazquezcamp, me puedes compartir un correo por el cual me pueda comunicar contigo por favor.

saludos

**Comment by vazquezcamp** [comment]
Claro es Israel.vazquez@ancient.mx

**Comment by vazquezcamp** [comment]
> Hola @vazquezcamp , me puedes compartir un correo por el cual me puedes comunicar contigo por favor.
> 
> saludos

Claro es Israel.vazquez@ancient.mx

**Comment by silvaGarduno** [comment]
@vazquezcamp podrías probar con el siguiente link por favor
https://github.com/conekta/conekta-woocommerce/tree/conekta_woocomerce_4
descargar el zip y realiza las pruebas para ver si ya no te sigue mandando el mismo error

**Comment by silvaGarduno** [comment]
Hay una nueva versión del plugin "3.0.7", antes de instalar, por favor des-instalar la versión que tienes instalada actualmente, borra cache e instala el nuevo plugin, con esto tu problema se debe solucionar
