### ISSUE TITLE
Error: amount" no es mayor a -1.

### ISSUE THREAD

**Issue by capitanjan** [conekta/conekta-woocommerce#118]
Este error aparece cuando los clientes quieren pagar con tarjeta. Con OXXO pay funciona sin problemas. Este error ya lo había corregido bajando la ulrima version de github, pero re-aparecio en nuestro Blog https://probioteca.mx. 
WP: Versión 5.3.2
Woocommerce: 4.0.1
Mi correo es jan@comerciarte.com

**Comment by silvaGarduno** [comment]
Podrías probar con el siguiente link por favor https://github.com/conekta/conekta-woocommerce/tree/conekta_woocomerce_4

Recuerda descargar el zip de esa página, me dices como te fue

**Comment by silvaGarduno** [comment]
Hay una nueva versión del plugin "3.0.7" la pueden descargar directamente desde su página de wordpress, antes de instalar por favor borren el cache y después realicen la instalación del plugin de conekta.

Link para borrar cache de wordpress
https://www.lucushost.com/blog/borrar-cache-wordpress/
