### ISSUE TITLE
Error: amount" no es mayor a -1

### ISSUE THREAD

**Issue by redeschamuco** [conekta/conekta-woocommerce#122]
Al momento de querer pagar una compra, la página arroja ese error.

**Comment by silvaGarduno** [comment]
Hola @redeschamuco 

Hay una nueva version "3.0.7", para solucionar este error, lo que debes hacer es eliminar el plugin que tienes actualmente instalado, borrar cache e instalar el nuevo plugin.

**Comment by redeschamuco** [comment]
Hice todo lo que me recomendaste y mi problema se solucionó completamente. Muchas gracias.
