### ISSUE TITLE
Error: amount" no es mayor a -1

### ISSUE THREAD

**Issue by AkrosSinclair** [conekta/conekta-woocommerce#123]
Hola, he tenido este problema y no he conseguido solucionarlo. Ya reinstalé la versión de Conekta y limpié el caché y sigue sin funcionarme.
Actualmente estoy trabajando con lo siguiente:
Wordpress: 5.4.2
WooCommerce: 4.2.0
Conekta: 3.0.7

Gracias.

**Comment by silvaGarduno** [comment]
@AkrosSinclair me puedes compartir tu correo por favor.

**Comment by AkrosSinclair** [comment]
oscartellez_@hotmail.com
