### ISSUE TITLE
antifraud_info where does it come from?

### ISSUE THREAD

**Issue by davidvexel** [conekta/conekta-woocommerce#49]
I've been getting an issue regarding a trip_id missing value on my wc checkout page. I reviewed the REST api docs and I see you have this anti fraud value, but not sure where does it come from. I'm just trying to figure out how to solve this issue in my site, it's happening either with oxxo cash or cc. Please see the attached screenshot.

![antifraud](https://cloud.githubusercontent.com/assets/8060793/26531271/718dc89c-43ab-11e7-84b0-dc430425fc38.png)

Additionally, I saw a lot of 422 error responses in the Conekta admin http log, with this conent:

`{
	"details": [
		{
			"debug_message": "The \"line_items at index 0 attribute antifraud_info attribute trip_id\" is missing.",
			"message": "El parametro trip_id\" es requerido.",
			"param": "line_items.0.antifraud_info.trip_id",
			"code": "conekta.errors.parameter_validation.line_items.antifraud_info.trip_id.missing"
		},
		{
			"debug_message": "The \"line_items at index 0 attribute antifraud_info attribute driver_id\" is missing.",
			"message": "El parametro driver_id\" es requerido.",
			"param": "line_items.0.antifraud_info.driver_id",
			"code": "conekta.errors.parameter_validation.line_items.antifraud_info.driver_id.missing"
		},
		{
			"debug_message": "The \"line_items at index 0 attribute antifraud_info attribute ticket_class\" is missing.",
			"message": "El parametro ticket_class\" es requerido.",
			"param": "line_items.0.antifraud_info.ticket_class",
			"code": "conekta.errors.parameter_validation.line_items.antifraud_info.ticket_class.missing"
		},
		{
			"debug_message": "The \"line_items at index 0 attribute antifraud_info attribute pickup_latlon\" is missing.",
			"message": "El parametro pickup_latlon\" es requerido.",
			"param": "line_items.0.antifraud_info.pickup_latlon",
			"code": "conekta.errors.parameter_validation.line_items.antifraud_info.pickup_latlon.missing"
		},
		{
			"debug_message": "The \"line_items at index 0 attribute antifraud_info attribute dropoff_latlon\" is missing.",
			"message": "El parametro dropoff_latlon\" es requerido.",
			"param": "line_items.0.antifraud_info.dropoff_latlon",
			"code": "conekta.errors.parameter_validation.line_items.antifraud_info.dropoff_latlon.missing"
		},
		{
			"debug_message": "The \"customer_info attribute antifraud_info attribute paid_transactions\" is missing.",
			"message": "El parametro paid_transactions\" es requerido.",
			"param": "customer_info.antifraud_info.paid_transactions",
			"code": "conekta.errors.parameter_validation.customer_info.antifraud_info.paid_transactions.missing"
		},
		{
			"debug_message": "The \"customer_info attribute antifraud_info attribute account_created_at\" is missing.",
			"message": "El parametro account_created_at\" es requerido.",
			"param": "customer_info.antifraud_info.account_created_at",
			"code": "conekta.errors.parameter_validation.customer_info.antifraud_info.account_created_at.missing"
		},
		{
			"debug_message": "The \"customer_info attribute antifraud_info attribute first_paid_at\" is missing.",
			"message": "El parametro first_paid_at\" es requerido.",
			"param": "customer_info.antifraud_info.first_paid_at",
			"code": "conekta.errors.parameter_validation.customer_info.antifraud_info.first_paid_at.missing"
		},
		{
			"debug_message": "\"shipping_contact attribute address attribute street1\" is too short.",
			"message": "street1\" contiene menos de 1 caracteres.",
			"param": "shipping_contact.address.street1",
			"code": "conekta.errors.parameter_validation.shipping_contact.address.street1.too_short"
		},
		{
			"debug_message": "Invalid format for \"shipping_contact attribute address attribute city\"",
			"message": "Formato inválido para city\"",
			"param": "shipping_contact.address.city",
			"code": "conekta.errors.parameter_validation.shipping_contact.address.city.invalid"
		},
		{
			"debug_message": "\"shipping_contact attribute address attribute country\" is too short.",
			"message": "country\" contiene menos de 1 caracteres.",
			"param": "shipping_contact.address.country",
			"code": "conekta.errors.parameter_validation.shipping_contact.address.country.too_short"
		}
	],
	"object": "error",
	"type": "parameter_validation_error",
	"log_id": "592b126bb795b02ad5268e86"
}`

**Comment by KarlaRobinson** [comment]
Hi David!
If you write to soporte@conekta.com and include the email with which you access your Conekta admin, I can adjust the configuration of your account. (You can put my name in the subject line.)

-Karla
