### ISSUE TITLE
WordPress plugin - invalid_payment_type

### ISSUE THREAD

**Issue by alanalvespi** [conekta/conekta-woocommerce#5]
Instale el plugin de Conekta para WooCommerce y al hacer pagos en produccion y pruebas en el checkout sale el mensaje: "Error: Tipo de método de pago inválido o faltante. Los valores aceptados son: card, cash o bank."

Las versiones son compatibles con el plugin:
- PHP 5.44.42
- WooCommerce 2.4.8 
- Conekta plugin 0.2.1
- Wordpress 4.4.2

Trate de instalar y desinstalar el plugin, activar y desactivar el plugin. No ocurre nada distinto. La respuesta que obtengo en Conekta es:

```
{
  "object": "error",
  "type": null,
  "message": "Payment method invalid or missing. Accepted values are: card , cash or bank.",
  "message_to_purchaser": "Tipo de método de pago inválido o faltante. Los valores aceptados son: card, cash o bank.",
  "param": "payment_type",
  "code": "invalid_payment_type"
}
```

**Comment by Augustino7** [comment]
Hola yo tambien tengo el mismo error, como lo pudiste resolver?, mi correo es augustino@gmail.com

**Comment by Janee** [comment]
Hola @Augustino7 el detalle fue que el theme de Wordpress afectaba jQuery y posteriormente ConektaJS. Al depurarse se solucionó, si gustas puedes enviar un correo a soporte@conekta.io para darte atención personalizada :)

**Comment by Augustino7** [comment]
ok, gracias, voy a tratar de solucionarlo, ese error, parece ser que nos falta un array que asi se llama payment_method, de hecho acabo de mandarles un correo, pero todavia estoy esperando su respuesta

**Comment by KarlaRobinson** [comment]
Ante cualquier detalle con un plugin es importante ver si estas con la version mas nueva, porque puede ser que ya se solucionó. https://github.com/conekta/conekta-woocommerce/releases
