### ISSUE TITLE
Remplazar imágenes

### ISSUE THREAD

**Issue by str** [conekta/conekta-woocommerce#52]
¿Es posible remplazar las imágenes en el checkout del WooCommerce con imágenes del template? (esta por ejemplo: wp-content/plugins/conekta-woocommerce/images/oxxopay.png)  Esto, para poder adaptarlo mejor al tema.

Gracias.

**Comment by Janee** [comment]
Hola @str sí, sería renombrar las imágenes que deseas en:
https://github.com/conekta/conekta-woocommerce/tree/master/images

Aquí podrás encontrar nuestro contenido oficial, incluyendo archivos .AI: http://bit.ly/ckta-resources

O bien, editar las imagenes con los colores convenientes para tu sitio.

**Comment by Janee** [comment]
@str ¿Haz intentado con un asset JS en tu theme?

Un javascript que sustituya el src de las imagenes por las tuya, o bien, en la sección de configuración que tenemos en cada método de pago.

![captura de pantalla 2017-08-03 a la s 11 16 50](https://user-images.githubusercontent.com/4097278/28934829-fd73c8b8-7847-11e7-9e62-fb443eaeedd4.png)

Aquí ejemplo de como el pago con tarjeta cambia la imagen:
https://github.com/conekta/conekta-woocommerce/blob/master/conekta_card_gateway.php#L32

**Comment by str** [comment]
Muchas gracias.
