### ISSUE TITLE
Order properties should not be accesed directly. Called status incorrectly.

### ISSUE THREAD

**Issue by sifonsecac** [conekta/conekta-woocommerce#56]
In conekta_card_gateway.php line 211.

```
if ($this->order->status == 'completed')
                return;
```

Should be.

```
 if ($this->order->get_status() == 'completed')
                return;
```

In conekta_cash_gateway.php line 151

`if ( $this->instructions && 'on-hold' === $order->status ) {`

should be.

`if ( $this->instructions && 'on-hold' === $order->get_status() ) {`

And line 257.

```
 if ($this->order->status == 'completed')
                return;
```

should be

 ```
 if ($this->order->get_status() == 'completed')
                return;
```

**Comment by JoValo** [comment]
@sifonsecac. We have fixed this, we invite you to download our beta for WooCommerce 3
`git@github.com:conekta/conekta-woocommerce.git`

**Comment by KarlaRobinson** [comment]
The newest beta versión will also be available on the Wordpress Marketplace shortly, we hope they approve and release it by this month.
https://es.wordpress.org/plugins/search/conekta/
