### ISSUE TITLE
We have an error in: syntax error, unexpected '[' in conekta_gateway_helper.php on line 83 

### ISSUE THREAD

**Issue by agbi85** [conekta/conekta-woocommerce#64]
This error appear wen activate the plugin, i'm using the wp version 4.7.5 can u help me?

**Comment by JoValo** [comment]
Hi @agbi85 what version of woocommerce and our plugin do you have? You can try the new version of our plugin in the marketplace or downloading it from our repo in Github

**Comment by agbi85** [comment]
Hi @JoValo, i used the 4.7.5 wp version  and the last version of conekta, i'm loading the plugin and install correctly but when i proceed to activate show me the error in line 80 in the conekta_gateway_helper.php file.

**Comment by eduardoconekta** [comment]
@agbi85 Hi,I have deployed a new woocommerce store with Conekta plugin instalation  and there is no error activating it, thats the right way to install 
![inicio](https://user-images.githubusercontent.com/26972091/29421715-8d689af4-833b-11e7-8668-0fb64298f80d.gif)
![inicio1](https://user-images.githubusercontent.com/26972091/29421717-8d6c57ac-833b-11e7-8bd6-55fcf213d7b9.gif)
![inicio2](https://user-images.githubusercontent.com/26972091/29421714-8d669ba0-833b-11e7-9aa5-4275d8f7e0cf.gif)
![inicio3](https://user-images.githubusercontent.com/26972091/29421716-8d6c0f7c-833b-11e7-9ac1-b29485273021.gif)

![inicio5](https://user-images.githubusercontent.com/26972091/29421718-8d6cc1f6-833b-11e7-8834-d6f22a0eff47.gif)
![inicio6](https://user-images.githubusercontent.com/26972091/29421721-8d7a957e-833b-11e7-9448-865742e8ffc4.gif)

![inicio8](https://user-images.githubusercontent.com/26972091/29421720-8d79d396-833b-11e7-9814-1aeb61ba7e2f.gif)
