### ISSUE TITLE
Error when customer tries to pay under 'my-account'

### ISSUE THREAD

**Issue by decimoseptimo** [conekta/conekta-woocommerce#67]
For offline payments, If a customer tries to pay (change payment method, retrieve payment references, whatever) from '/mi-account/orders/' where a 'pay' button has been enabled.
![sin titulo4](https://user-images.githubusercontent.com/16873203/29535253-07ace6b4-866e-11e7-9c1b-5c835c0d607e.png)

Error is thrown.
![sin titulo5](https://user-images.githubusercontent.com/16873203/29535247-025bcd92-866e-11e7-93bd-f665a2970afe.png)

Where latest payment information should be shown.

**Comment by KarlaRobinson** [comment]
@decimoseptimo
A support agent has answered your email :)

For any other users we suggest updating to the newest version on the Wordpress Marketplace:

https://es.wordpress.org/plugins/search/conekta/
