### ISSUE TITLE
Error of description and instructions for Coneckta SPEI

### ISSUE THREAD

**Issue by decimoseptimo** [conekta/conekta-woocommerce#68]
Given the fields 'description' and 'instructions' being set.
![sin titulo3](https://user-images.githubusercontent.com/16873203/29535442-af6ac1d2-866e-11e7-9307-cb5850c86d8d.png)

Description does not match in checkout
![sin titulo](https://user-images.githubusercontent.com/16873203/29535824-3ce55e5e-8670-11e7-881e-f11fe9ae45df.png)

Instructions are not present in order received, which can be very confusing. Also font size for the reference number is very small.
![sin titulo2](https://user-images.githubusercontent.com/16873203/29535440-adb66936-866e-11e7-809e-c85cf14a70a4.png)

**Comment by eduardoconekta** [comment]
@decimoseptimo Gracias por notificarnos, estamos corrigiendo algunos bugs y esto saldrá en el siguiente release y lo lanzaremos en marketplace para que puedas actualizar el plugin directo desde wordpress, la fecha de release sera la siguiente semana antes del dia viernes, aun así nosotros te notificamos el día que se haga el release.
En concreto esos campos pensamos que no son tan relevantes para los usuarios asi que los removeremos y agregaremos algunos estándar para que ademas puedan tener traducción, tambien tomaremos en cuenta que la clabe sea mas grande

**Comment by decimoseptimo** [comment]
Entonces esperare la actualizacion, nada mas me gustaria agregar que es buena idea anexar algun tipo de instrucciones al momento de proporcionar la CLABE interbancaria.

**Comment by JoValo** [comment]
@decimoseptimo esto ya esta listo
