### ISSUE TITLE
Incompatibilidad con PHP 7

### ISSUE THREAD

**Issue by lmsanr** [conekta/conekta-woocommerce#70]
Hola,

Actualmente uso en mi sitio la versión de PHP 7 que es la mínima recomendada por WordPress.

El plugin tiene las siguientes incompatibilidades:

> FILE: /home/avisofor/public_html/marialuisacollectionmx/wp-content/plugins/conekta-payment-gateway/lib/conekta-php/lib/Conekta/Resource.php
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
> FOUND 1 ERROR AFFECTING 1 LINE
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
>  12 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> 
> FILE: /home/avisofor/public_html/marialuisacollectionmx/wp-content/plugins/conekta-payment-gateway/lib/conekta-php/lib/Conekta/Object.php
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
> FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
>   8 | ERROR   | 'object' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)
>  57 | WARNING | Method name "Object::__toJSON" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------

No sé cuánto pueda afectar ya que sigo probando en modo sandbox, si encuentro algo más se los comparto.

**Comment by JoValo** [comment]
@lmsanr Gracias por compartirnos el caso, lo tomaremos en cuenta para el siguiente refactor de la librería, lo estaremos lanzando en un periodo de 1 a 2 meses mas.

**Comment by lmsanr** [comment]
Gracias

**Comment by JoValo** [comment]
Hola @lmsanr estamos trabajando en este issue, muchas gracias por tus observaciones esperamos lanzarlo antes de esta semana

**Comment by eduardoconekta** [comment]
@lmsanr ya se ha liberado este feature, gracias por reportarlo (solo para woocommerce 3 en adelante )
