### ISSUE TITLE
no funciona con WooCommerce All Discounts Lite

### ISSUE THREAD

**Issue by ropic** [conekta/conekta-woocommerce#71]
Recibo el siguiente error:

"amount" no es mayor a -1."

Versión de woo commerce 3.1.2, al deshabilitar el módulo si funciona el pago, con otras formas de pago sin problema

**Comment by JoValo** [comment]
Hola @ropic 
Tienes algún plugin instalado sobre descuentos? O algo externo que este modificando esa parte?

**Comment by ropic** [comment]
Así es, estábamos usando: https://wordpress.org/plugins/woo-advanced-discounts/

Nuestra solución fue: 

1. Crear un cupón con el descuento
2. Usar https://wordpress.org/plugins/woocommerce-auto-added-coupons/ para aplicarlo automáticamente

Saludos

**Comment by JoValo** [comment]
Gracias @ropic por tus comentarios y compartirnos tu solución
