### ISSUE TITLE
Conekta - Woocommerce Error: Formato inválido para receiver"

### ISSUE THREAD

**Issue by cataboom123** [conekta/conekta-woocommerce#77]
Estoy habilitando el pago por por Woocommerce con Conekta y me da este error:
Error: Formato inválido para receiver"
No sé qué puede ser. Tengo la versión más actualizada del plugin.
Si alguien le ha pasado lo mismo le agradezco la solución.

Gracias

**Comment by JoValo** [comment]
Hola @cataboom123 puedes habilitar el debug mode de tu tienda para poder saber que pasa, también me puedes compartir que versión de PHP, Wordpress y de nuestro plugin tienes.

**Comment by cataboom123** [comment]
Hola @JoValo,
Gracias por responder.
Habilité la versión debug, estos son los errores que salen: 

Notice: Undefined variable: args in /public_html/wp-content/plugins/woocommerce-products-filter/index.php on line 2800
**Es un error de otro plugin que ya había resuelto.

Notice: load_plugin_textdomain was called with an argument that is deprecated since version 2.7.0 with no alternative available. in /public_html/wp-includes/functions.php on line 4026

Con el Debug activado ya no me deja escoger el medio de pago, no probar, en el Checkhout.
Tengo la versión Versión 3.0.1
PHP 5.6
Wordpress 4.8.2

Quedo atenta a tu respuesta.

**Comment by JoValo** [comment]
@cataboom123 me podrías compartir un log de la orden que estas generando, al parecer están enviando algo diferente a un string en el parametro de receiver

**Comment by cataboom123** [comment]
@JoValo acabo de responderte al email. 
Sigo atenta.
