### ISSUE TITLE
Version incorrecta

### ISSUE THREAD

**Issue by decimoseptimo** [conekta/conekta-woocommerce#78]
Probe la version 3.0.1, al instalarla esta se identifica en woocommerce como "Versión 2.0.12".
Ademas en woocommerce no se acostumbra que la carpeta raiz del plugin cambie de nombre en cada version.

Cual es proceso para que salga de beta? considerando que la 3.0.0 es la que inicia compatibliiad con WC 3, ya deberia ser estable no...

**Comment by cocoliso** [comment]
Recibo un error. Lo instalé en la versión más actual de WP y WC... creo que debe estar actualizado. ¿Cuándo podemos contar con la versión correcta? Nos urge hacer pruebas.

Fatal error: Can't use method return value in write context in /home4/huestafi/public_html/tequilacocula.com/2017/wp-content/plugins/conekta-woocommerce-3.0.1/conekta_gateway_helper.php on line 286
