### ISSUE TITLE
La URL de woocommerce para recibir los POST de conekta es incorrecta

### ISSUE THREAD

**Issue by HumbertoBoone** [conekta/conekta-woocommerce#80]
No había estado recibiendo los posts en la URL que ponen en el tutorial; http://tusitio.com/wc-api/WC_Conekta_Cash_Gateway

Investigando en la documentacion de woocommerce  encontré que la sintaxis para que funcionara debería ser asi: http://tusitio.com/?wc-api=WC_Conekta_Cash_Gateway

Ya hice pruebas y esta si funcionó

**Comment by JoValo** [comment]
Hola @HumbertoBoone me puedes compartir la documentación donde encontraste esa información.
La documentación donde consultamos para hacer ese cambio es la siguiente: https://docs.woocommerce.com/document/wc_api-the-woocommerce-api-callback/ donde señala que para versión de WooCommerce 2+ se puede seguir usando la versión que nos indicas o el endpoint de WC, la versión actual de plugin es para WooCommerce 3+ por ello ocupamos `http://yoursite.com/wc-api/CALLBACK/
`

**Comment by HumbertoBoone** [comment]
No fui muy explicito arriba, mis disculpas. Cuando recién instale woocommerce estaba usando la versión 2 me parece y no me funcionaba la url del tutorial luego actualice a la versión 3+ y aun así tampoco funcionaba entonces pensé en usar el callback de woocommerce 2.0 o anterior y esta si me funciono sin problemas. No se ha que se deba la verdad probablemente el error esta en woocommerce (incluso hice pruebas en varias versiones diferentes) o la documentación es incorrecta. 
Adjunto el status de los webhooks del panel con los dos tipos de callback
![captura de pantalla 39](https://user-images.githubusercontent.com/7479196/33741393-60b07dfa-db61-11e7-8735-c63a3bbf120d.png)

**Comment by eduardoconekta** [comment]
hola @HumbertoBoone creo que eso se debe a como tienes configurados tus links en tu sitio (permalinks) pueden estar mapeados como pretty urls `api/WC_Conekta_C...` o como parameters `api=WC_C...` pero al final los dos son lo mismo
