### ISSUE TITLE
Cannot use Conekta\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by salasmx** [conekta/conekta-woocommerce#81]
Fatal error: Cannot use Conekta\Object as Object because 'Object' is a special class name in /Users/carlos/Sites/yu-store/web/app/plugins/conekta-woocommerce-3.0.2/lib/conekta-php/lib/Conekta/Util.php on line 5

**Comment by JoValo** [comment]
Hola @salasmx puedes actualizar la versión de la librería de PHP https://github.com/conekta/conekta-php.

Este error se presenta en versiones de PHP 7+ actualmente no hemos actualizado la librería de PHP en el plugin pero lo haré a la brevedad en Github y también en Marketplace
