### ISSUE TITLE
compatibilidad php 7.0

### ISSUE THREAD

**Issue by ramonqui** [conekta/conekta-woocommerce#85]
Hola, intento usar su plugin con php 7.0, sin embargo me aparece el siguiente problema.
..../wp-content/plugins/conekta-woocommerce-3.0.2/lib/conekta-php/lib/Conekta/Resource.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 12 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)
----------------------------------------------------------------------------------------------------------------------------------------------------------------

.....wp-content/plugins/conekta-woocommerce-3.0.2/lib/conekta-php/lib/Conekta/Object.php

----------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by eduardoconekta** [comment]
@ramonqui la version 3.0.3 de nuestro plugin liberado la semana pasada ya no tiene este inconveniente
