### ISSUE TITLE
Fatal error en PHP 7.2

### ISSUE THREAD

**Issue by lmsanr** [conekta/conekta-woocommerce#86]
Con PHP 7.2 aparece el siguiente error:

> Fatal error: Cannot use Conekta\Object as Object because 'Object' is a special class name in /wp-content/plugins/conekta-payment-gateway/lib/conekta-php/lib/Conekta/Util.php on line 5

Aunque he probado y funciona bien com PHP 7.0 y 7.1, WordPress recomienda versión mínima de 7.2

https://wordpress.org/about/requirements/

Ojalá lo puedan considerar para próximos releases.

**Comment by eduardoconekta** [comment]
@lmsanr listo, ya tenemos en marketplace de wordpress la version 3.0.3 del plugin que puedes descargar directo de tu admin compatible con wordpress 7.2
