### ISSUE TITLE
Fatal error: Can't use method return value in write context in .../wp-content/plugins/conekta-payment-gateway/conekta_gateway_helper.php on line 286

### ISSUE THREAD

**Issue by anaja7** [conekta/conekta-woocommerce#91]
Mi página me regresa este error: Fatal error: Can't use method return value in write context in .../wp-content/plugins/conekta-payment-gateway/conekta_gateway_helper.php on line 286 
Al activar el plugin de conekta.

Que puedo hacer??

**Comment by eduenriquez** [comment]
@anaja7 desde donde descargaste el plugin ? tenemos una version en marketplace de wordpress es decir puedes descargar el plugin directo de la session de plugins de tu wordpress 
https://es-mx.wordpress.org/plugins/conekta-payment-gateway/

**Comment by eduenriquez** [comment]
Y con respecto al plugin en tu tienda 
¿Pides actualmente los datos de envio ?
¿tienes algun un plugin de envio que pueda estar interfiriendo  ? 

El problema es causado ya que en la linea que mencionas https://github.com/conekta/conekta-woocommerce/blob/master/conekta_gateway_helper.php#L286 nosotros validamos que la primera direccion de envio no sea nula, pero al parecer cuando se intenta concretar la orden esta llevando ese atributo `get_shipping_address_1`

**Comment by eliasmaxil** [comment]
Hola. Mismo mensage con error fatal el L286. Yo descargue el plugin siguiendo estas [instrucciones](https://developers.conekta.com/plugins/woocommerce) de https://github.com/conekta/conekta-woocommerce/releases que le llevo a la version 3.0.5. 
En mi caso, estoy haciendo una pagina por primera vez en WP. Tengo WC installado y en mi caso, la pagina todavia no tiene pedidos u ordenes por lo tanto, tampoco direcciones de envio. El aviso me aparece directamente despues de abrir el zip de la version 3.0.5 y activarlo. De ahi pierdo todo el CMS de wordpress. Para recuperarlo necesito entrar al controlpanel de mi sitio y borrar el folder del plugin completo.

**Comment by eduenriquez** [comment]
@eliasmaxil podrías descargarlo desde marketplace de wordpress ? lo unico que tienes que hacer es entrar a plugins -> instalar nuevo -> buscar por conekta en la barra de búsqueda, seguido de eso le das a activar al recuadro del plugin y tendrías instalado el plugin de igual forma.
Me podrías confirmar si esa solución te sirve ?

**Comment by eliasmaxil** [comment]
Lo acabo de instalar desde el marketplace siguiendo tus instrucciones. Si encontre el plugin pero obtuve el mismo resultado. Error fatal en linea 286 [if (!empty($order->get_shipping_address_1()))]

**Comment by eduenriquez** [comment]
@eliasmaxil ok, gracias déjame replicar el error para poder solucionarlo, por lo mientras puedes seguir las mismas instrucciones de instalación de github con una version anterior https://github.com/conekta/conekta-woocommerce/releases/tag/v3.0.4

**Comment by eliasmaxil** [comment]
@eduenriquez, Instale la version 3.0.4 pero obtengo el mismo resultado en: wp-content/plugins/conekta-woocommerce-3.0.4/conekta_gateway_helper.php on line 286.

**Comment by eliasmaxil** [comment]
@eduenriquez, para agregar mas info, la pagina fue creada desde cero. Hasta ahora solo tengo los siguientes plugins activados: shortcodes-ultimate, woocommerce, wp-fastest-cache. Mi template es generatepress, que tiene otro plugin extra para hacer el tamplate premium (activado). 
PHP Version 5.4.45
System: Linux gatorXXXX.hostgator.com ?????.x86_64 #1 SMP .....
DB: mysql
Hice un archivo de phpinfo si es necesario. Lo preferiria enviar por un medio menos publico, si es necesario.

**Comment by eduenriquez** [comment]
@eliasmaxil no hace falta, estoy descartando que sea la version de PHP por le momento, me parece que ya detecte donde se encuentra el bug, estoy haciendo un release dame 5 minutos para facilitartelo

**Comment by eduenriquez** [comment]
te facilito el nuevo release, me podrías confirmar si puedes instalarlo ?, https://github.com/conekta/conekta-woocommerce/releases/tag/v3.0.6 por cierto leyendo la parte que hace que retorne este error es por que en realidad las versiones menores a la 5.5 no soportan apuntar directamente a las referencias de objetos.

**Comment by eliasmaxil** [comment]
Perfecto @eduenriquez . La version 3.0.6 funciona! Gracias!
